project_name: undo
release:
  github:
    owner: aofekiko
    name: kubectl-undo
builds:
  - id: undo
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/aofekiko/kubectl-undo/pkg/version.version=
archives:
  - id: undo
    builds:
    - undo
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
