apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: undo
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/aofekiko/kubectl-undo/releases/download/v0.1.0/undo_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./undo"
      to: "."
    - from: LICENSE
      to: "."
    bin: "undo"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/aofekiko/kubectl-undo/releases/download/v0.1.0/undo_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./undo"
      to: "."
    - from: LICENSE
      to: "."
    bin: "undo"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/aofekiko/kubectl-undo/releases/download/v0.1.0/undo_windows_amd64.zip
    sha256: ""
    files:
    - from: "/undo.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "undo.exe"
  shortDescription: A new plugin
  homepage: https://github.com/aofekiko/kubectl-undo
  caveats: |
    Usage:
      $ kubectl undo

    For additional options:
      $ kubectl undo --help
      or https://github.com/aofekiko/kubectl-undo/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
